[package]
name = "roxycloud-app"
version.workspace = true
description = "RoxyCloud desktop client"
edition.workspace = true
license.workspace = true
authors.workspace = true
repository.workspace = true
rust-version.workspace = true

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
roxycloud-client = { workspace = true }
roxycloud-core = { workspace = true }

tauri = { version = "2", features = [] }
tokio = { workspace = true }
serde = { workspace = true }

[lints]
workspace = true
